#!/usr/bin/python3
import os
import sys
import time

"""
Scans a directory recursively for
valid service directories.
"""

if len(sys.argv) < 2:
    sys.exit("Please give searchpath as an argument")

PATH = os.environ.get("PATH")
os.environ.clear()
os.environ["PATH"] = PATH
os.environ["SI_SCAN_START"] = str(int(time.time()))
os.execvp("si-scanner", sys.argv)
