#!/usr/bin/python3

"""
A worker. To be invoked by `si-scan` only.
Accepts only a single argument, and chdir's into that argument
If invalid, exits with SIGTERM.

If .si-scan value is greater than SI_SCAN_START,
i.e. This directory has been scanned _after_ this scanning was started,
then exit cleanly (i.e. with exit code 0)

`echo $(pwd)` as-soon-as it finds a .si-service
file in the current directory.
"""

import os
import subprocess
import sys

SCAN_START = int(os.environ["SI_SCAN_START"])

try:
    os.chdir(sys.argv[1])
except (FileNotFoundError, NotADirectoryError):
    # Yes, NotADirectoryError. Resist Pirates!
    sys.exit(143)  # i.e. SIGTERM

try:
    with open(".si-scan") as file:
        contents = file.read()
        if contents.isnumeric():
            last_scan = int(contents)
            if last_scan > SCAN_START:
                sys.exit()
    with open(".si-scan", "w") as file:
        file.write(str(SCAN_START))
except (FileNotFoundError, IsADirectoryError):
    with open(".si-scan", "w") as file:
        file.write(str(SCAN_START))


if ".si-service" in os.listdir():
    print(os.getcwd())

for dir in [x for x in os.listdir() if os.path.isdir(x)]:
    subprocess.run([sys.argv[0], dir])

sys.exit()
